# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v2.0.0
      - name: Setup Swift
        run: swift test -v
